"""Made-up cooking recipe dataset for demonstrating ARF.

50 recipes organized hierarchically:
  Cuisine (root) → Category → Recipe → Steps (children)
"""

RECIPES = [
    # ── Italian ──
    {
        "title": "Classic Margherita Pizza",
        "cuisine": "Italian",
        "category": "Main Course",
        "text": "A traditional Neapolitan pizza with San Marzano tomato sauce, fresh mozzarella, basil leaves, and extra virgin olive oil on a thin, charred crust.",
        "steps": [
            {"title": "Prepare dough", "text": "Mix 500g tipo 00 flour, 325ml water, 10g salt, 3g yeast. Knead for 10 minutes until smooth and elastic. Let rise for 8 hours at room temperature."},
            {"title": "Shape and top", "text": "Stretch dough into a 12-inch circle. Spread crushed San Marzano tomatoes. Add torn fresh mozzarella. Drizzle olive oil."},
            {"title": "Bake", "text": "Bake at 500°F on a preheated pizza stone for 8-10 minutes until crust is charred and cheese is bubbly. Top with fresh basil leaves."},
        ],
    },
    {
        "title": "Risotto alla Milanese",
        "cuisine": "Italian",
        "category": "Main Course",
        "text": "Creamy saffron-infused risotto from Milan, made with Arborio rice, bone marrow, white wine, and Parmigiano-Reggiano.",
        "steps": [
            {"title": "Toast rice", "text": "Melt butter in a heavy pan. Add finely diced onion and cook until translucent. Add 320g Arborio rice and toast for 2 minutes."},
            {"title": "Add saffron", "text": "Dissolve 0.5g saffron threads in warm broth. Deglaze rice with 150ml white wine. Begin adding saffron broth one ladle at a time, stirring constantly."},
            {"title": "Finish", "text": "After 18 minutes, remove from heat. Stir in 50g cold butter and 80g grated Parmigiano. Rest 2 minutes before serving."},
        ],
    },
    {
        "title": "Tiramisu",
        "cuisine": "Italian",
        "category": "Dessert",
        "text": "Classic Italian layered dessert with espresso-soaked ladyfingers, mascarpone cream, and cocoa powder.",
        "steps": [
            {"title": "Make cream", "text": "Whisk 6 egg yolks with 150g sugar until pale. Fold in 500g mascarpone. In a separate bowl, whip 300ml heavy cream to stiff peaks and fold in."},
            {"title": "Assemble layers", "text": "Briefly dip ladyfingers in cooled espresso mixed with 2 tbsp Marsala. Layer in a dish, alternating with mascarpone cream."},
            {"title": "Chill and serve", "text": "Refrigerate for at least 6 hours or overnight. Dust generously with cocoa powder before serving."},
        ],
    },
    {
        "title": "Pasta Carbonara",
        "cuisine": "Italian",
        "category": "Main Course",
        "text": "Roman pasta dish made with guanciale, egg yolks, Pecorino Romano, and black pepper. No cream.",
        "steps": [
            {"title": "Prepare sauce", "text": "Whisk 4 egg yolks with 2 whole eggs. Add 100g finely grated Pecorino Romano and generous black pepper."},
            {"title": "Cook guanciale", "text": "Cut 200g guanciale into strips. Render in a cold pan over medium heat until crispy, about 8 minutes."},
            {"title": "Combine", "text": "Cook 400g spaghetti until al dente. Toss hot pasta with guanciale and fat, then quickly stir in egg mixture off heat. The residual heat creates a creamy sauce."},
        ],
    },
    {
        "title": "Bruschetta al Pomodoro",
        "cuisine": "Italian",
        "category": "Appetizer",
        "text": "Toasted bread rubbed with garlic and topped with diced tomatoes, fresh basil, olive oil, and sea salt.",
        "steps": [
            {"title": "Prepare topping", "text": "Dice 6 ripe Roma tomatoes. Toss with torn basil, minced garlic, olive oil, salt, and balsamic vinegar. Let marinate 15 minutes."},
            {"title": "Toast bread", "text": "Slice a rustic Italian loaf into 1cm slices. Brush with olive oil and grill or broil until golden. Rub with a halved garlic clove."},
        ],
    },
    # ── Japanese ──
    {
        "title": "Tonkotsu Ramen",
        "cuisine": "Japanese",
        "category": "Main Course",
        "text": "Rich pork bone broth ramen from Fukuoka with thin noodles, chashu pork, soft-boiled egg, and green onions.",
        "steps": [
            {"title": "Make broth", "text": "Boil 2kg pork leg bones and 1kg pork back fat in water for 12-18 hours on a rolling boil. The collagen breaks down into a milky white, intensely rich broth."},
            {"title": "Prepare toppings", "text": "Roll and tie pork belly. Braise in soy sauce, mirin, sake, and sugar for 2 hours until tender. Slice thinly. Marinate soft-boiled eggs in the braising liquid for 4 hours."},
            {"title": "Assemble", "text": "Cook thin straight noodles for 45 seconds. Place in bowl, ladle hot broth over. Top with chashu, marinated egg, sliced green onions, nori, and pickled ginger."},
        ],
    },
    {
        "title": "Sushi Rice",
        "cuisine": "Japanese",
        "category": "Side Dish",
        "text": "Perfectly seasoned short-grain rice for sushi, flavored with rice vinegar, sugar, and salt.",
        "steps": [
            {"title": "Wash rice", "text": "Rinse 3 cups short-grain Japanese rice in cold water 5-6 times until water runs clear. Soak for 30 minutes, then drain."},
            {"title": "Cook and season", "text": "Cook rice in a rice cooker with equal water. Mix 80ml rice vinegar, 30g sugar, and 10g salt. Fold seasoning into hot rice using a cutting motion. Fan to cool while mixing."},
        ],
    },
    {
        "title": "Miso Soup",
        "cuisine": "Japanese",
        "category": "Soup",
        "text": "Traditional Japanese soup made with dashi stock, miso paste, tofu cubes, and wakame seaweed.",
        "steps": [
            {"title": "Make dashi", "text": "Soak 10g kombu in 1L cold water for 30 minutes. Heat slowly until just before boiling. Remove kombu, add 20g bonito flakes, steep 5 minutes, and strain."},
            {"title": "Add miso", "text": "Heat dashi to a gentle simmer. Add cubed silken tofu and rehydrated wakame. Dissolve 3 tbsp white miso paste in a small amount of dashi, then stir into the pot. Never boil after adding miso."},
        ],
    },
    {
        "title": "Chicken Katsu Curry",
        "cuisine": "Japanese",
        "category": "Main Course",
        "text": "Crispy breaded chicken cutlet served with Japanese curry sauce over steamed rice. A comfort food staple.",
        "steps": [
            {"title": "Make curry", "text": "Sauté diced onion, carrot, and potato in oil. Add 800ml water and simmer until vegetables are tender. Break in Japanese curry roux blocks and stir until thickened."},
            {"title": "Prepare katsu", "text": "Pound chicken breast to even thickness. Season, dust with flour, dip in beaten egg, coat in panko breadcrumbs. Deep fry at 170°C for 6-7 minutes until golden."},
            {"title": "Serve", "text": "Slice katsu into strips. Arrange over steamed rice with curry sauce alongside. Garnish with pickled fukujinzuke."},
        ],
    },
    {
        "title": "Gyoza",
        "cuisine": "Japanese",
        "category": "Appetizer",
        "text": "Pan-fried Japanese dumplings filled with ground pork, cabbage, garlic, ginger, and sesame oil.",
        "steps": [
            {"title": "Make filling", "text": "Finely chop 200g cabbage, salt and squeeze dry. Mix with 300g ground pork, 2 cloves minced garlic, 1 tbsp grated ginger, soy sauce, sesame oil, and white pepper."},
            {"title": "Wrap and fold", "text": "Place 1 tbsp filling in center of each gyoza wrapper. Wet edges, fold in half, and create 5-6 pleats along one side to seal."},
            {"title": "Pan-fry", "text": "Heat oil in a nonstick pan. Place gyoza flat-side down. Fry 2 minutes until golden. Add 80ml water, cover, steam for 4 minutes. Remove lid and cook until water evaporates and bottoms are crispy."},
        ],
    },
    # ── Mexican ──
    {
        "title": "Tacos al Pastor",
        "cuisine": "Mexican",
        "category": "Main Course",
        "text": "Marinated pork tacos inspired by Lebanese shawarma, with achiote paste, pineapple, cilantro, and onion on corn tortillas.",
        "steps": [
            {"title": "Marinate pork", "text": "Blend 4 dried guajillo chiles, 2 chipotles in adobo, achiote paste, pineapple juice, vinegar, garlic, cumin, and oregano into a smooth paste. Coat 1kg thinly sliced pork shoulder. Marinate 4-24 hours."},
            {"title": "Cook", "text": "Layer marinated pork on a vertical spit with pineapple slices between layers. Roast, shaving off crispy edges as they cook. Alternatively, grill slices on high heat for 3-4 minutes per side."},
            {"title": "Assemble", "text": "Warm small corn tortillas. Top with chopped al pastor, diced pineapple, cilantro, diced white onion, and a squeeze of lime."},
        ],
    },
    {
        "title": "Guacamole",
        "cuisine": "Mexican",
        "category": "Appetizer",
        "text": "Fresh avocado dip with lime juice, cilantro, onion, jalapeño, and tomato. Best made tableside.",
        "steps": [
            {"title": "Prepare", "text": "Halve and pit 3 ripe Hass avocados. Scoop flesh into a molcajete or bowl. Add juice of 2 limes, 1/2 diced white onion, 1 seeded minced jalapeño, and salt."},
            {"title": "Mash and season", "text": "Mash to desired consistency with a fork — leave it chunky. Fold in diced tomato and chopped cilantro. Taste and adjust lime and salt. Serve immediately with warm tortilla chips."},
        ],
    },
    {
        "title": "Mole Poblano",
        "cuisine": "Mexican",
        "category": "Main Course",
        "text": "Complex Pueblan sauce made from dried chiles, chocolate, nuts, seeds, spices, and fruit, served over turkey or chicken.",
        "steps": [
            {"title": "Toast and soak chiles", "text": "Toast 6 ancho, 4 mulato, and 4 pasilla chiles on a dry comal until fragrant. Remove stems and seeds. Soak in hot water for 30 minutes."},
            {"title": "Build sauce", "text": "Fry raisins, almonds, peanuts, sesame seeds, tortilla pieces, and a slice of bread until golden. Blend soaked chiles with the fried ingredients, tomatoes, onion, garlic, cinnamon, cloves, and cumin."},
            {"title": "Cook mole", "text": "Fry the blended paste in lard for 20 minutes, stirring constantly. Add turkey broth to thin. Stir in 100g Mexican chocolate until melted. Simmer 1 hour, adjusting salt and sugar. Serve over poached turkey."},
        ],
    },
    {
        "title": "Elote (Mexican Street Corn)",
        "cuisine": "Mexican",
        "category": "Side Dish",
        "text": "Grilled corn on the cob coated with mayo, cotija cheese, chili powder, lime, and cilantro.",
        "steps": [
            {"title": "Grill corn", "text": "Shuck corn and grill over high heat, turning frequently, until charred in spots — about 10 minutes."},
            {"title": "Coat and serve", "text": "Brush hot corn with mayonnaise. Roll in crumbled cotija cheese. Sprinkle with Tajín or chili powder and a squeeze of lime juice. Garnish with cilantro."},
        ],
    },
    {
        "title": "Churros",
        "cuisine": "Mexican",
        "category": "Dessert",
        "text": "Fried dough sticks rolled in cinnamon sugar, often served with chocolate dipping sauce.",
        "steps": [
            {"title": "Make dough", "text": "Boil 240ml water with 60g butter, 1 tbsp sugar, and salt. Remove from heat, add 150g flour all at once, stir vigorously until a ball forms. Beat in 2 eggs one at a time."},
            {"title": "Fry", "text": "Pipe dough through a star-tipped pastry bag into 350°F oil. Fry 4-5 minutes until deep golden and crispy throughout. Drain on paper towels."},
            {"title": "Coat", "text": "Roll hot churros in a mixture of sugar and ground cinnamon. Serve with warm Mexican chocolate sauce for dipping."},
        ],
    },
    # ── Indian ──
    {
        "title": "Butter Chicken (Murgh Makhani)",
        "cuisine": "Indian",
        "category": "Main Course",
        "text": "Tandoori chicken pieces in a rich, creamy tomato-butter sauce with fenugreek, garam masala, and cream.",
        "steps": [
            {"title": "Marinate chicken", "text": "Mix yogurt, lemon juice, garam masala, turmeric, chili powder, and salt. Coat 800g chicken thigh pieces. Marinate at least 2 hours or overnight."},
            {"title": "Cook chicken", "text": "Grill or broil marinated chicken at high heat until charred edges form, about 8 minutes. Set aside."},
            {"title": "Make sauce", "text": "Sauté butter, garlic, and ginger. Add tomato puree, cook 20 minutes. Add cream, kasuri methi (dried fenugreek), garam masala, honey, and salt. Simmer until thickened. Add chicken pieces and coat in sauce."},
        ],
    },
    {
        "title": "Palak Paneer",
        "cuisine": "Indian",
        "category": "Main Course",
        "text": "Cubes of Indian cottage cheese in a smooth, spiced spinach gravy. A vegetarian staple of North Indian cuisine.",
        "steps": [
            {"title": "Blanch spinach", "text": "Blanch 500g fresh spinach in boiling water for 2 minutes. Transfer to ice water immediately. Blend into a smooth puree."},
            {"title": "Fry paneer", "text": "Cut 250g paneer into cubes. Pan-fry in ghee until light golden on all sides. Set aside."},
            {"title": "Build gravy", "text": "Sauté cumin seeds, diced onion, green chilies, ginger, and garlic in ghee. Add spinach puree, garam masala, and cream. Simmer 5 minutes. Add fried paneer cubes. Serve with naan or rice."},
        ],
    },
    {
        "title": "Samosa",
        "cuisine": "Indian",
        "category": "Appetizer",
        "text": "Crispy triangular pastry filled with spiced potatoes, peas, cumin, and green chilies. Deep-fried until golden.",
        "steps": [
            {"title": "Make filling", "text": "Boil and roughly mash 4 potatoes. Sauté cumin seeds, green chilies, ginger, and hing in oil. Add peas, mashed potato, garam masala, amchur powder, and cilantro."},
            {"title": "Prepare pastry", "text": "Mix 250g flour, ajwain seeds, salt, and 3 tbsp oil. Add water gradually to form a stiff dough. Roll thin circles, cut in half. Form cones and fill with potato mixture."},
            {"title": "Fry", "text": "Deep fry samosas at 150°C for 10-12 minutes until golden and crispy throughout. Serve with green chutney and tamarind chutney."},
        ],
    },
    {
        "title": "Biryani",
        "cuisine": "Indian",
        "category": "Main Course",
        "text": "Layered rice dish with spiced meat, saffron, fried onions, and fresh herbs. Slow-cooked with sealed lid (dum).",
        "steps": [
            {"title": "Prepare meat", "text": "Marinate 700g lamb or chicken in yogurt, ginger-garlic paste, biryani masala, red chili, turmeric, and salt for 2 hours. Cook in ghee until half done."},
            {"title": "Par-cook rice", "text": "Soak 500g aged basmati rice for 30 minutes. Boil with whole spices (cardamom, cinnamon, cloves, bay leaf) until 70% cooked. Drain."},
            {"title": "Layer and cook dum", "text": "In a heavy pot, layer: meat, rice, saffron milk, fried onions, mint, cilantro, ghee, and rose water. Seal with dough. Cook on lowest heat for 40 minutes. Rest 10 minutes before opening."},
        ],
    },
    {
        "title": "Naan Bread",
        "cuisine": "Indian",
        "category": "Side Dish",
        "text": "Soft, pillowy Indian flatbread traditionally baked in a tandoor oven. Brushed with garlic butter.",
        "steps": [
            {"title": "Make dough", "text": "Mix 400g flour, 1 tsp sugar, 1 tsp salt, 1 tsp baking powder, and 5g yeast. Add 150ml warm milk, 2 tbsp yogurt, and 2 tbsp oil. Knead 8 minutes until smooth. Rise 1 hour."},
            {"title": "Cook", "text": "Divide into 8 balls. Roll into teardrop shapes. Cook on a very hot cast iron skillet or under a broiler for 2-3 minutes per side until puffed and charred. Brush with garlic butter immediately."},
        ],
    },
    # ── Thai ──
    {
        "title": "Pad Thai",
        "cuisine": "Thai",
        "category": "Main Course",
        "text": "Stir-fried rice noodles with shrimp, tofu, bean sprouts, peanuts, lime, and tamarind sauce.",
        "steps": [
            {"title": "Make sauce", "text": "Mix 3 tbsp tamarind paste, 2 tbsp fish sauce, 2 tbsp palm sugar, and 1 tbsp rice vinegar. Set aside."},
            {"title": "Stir-fry", "text": "Soak 200g flat rice noodles in warm water 20 minutes. Stir-fry shrimp and pressed tofu in hot wok. Push aside, scramble 2 eggs. Add drained noodles and sauce. Toss until noodles absorb sauce."},
            {"title": "Serve", "text": "Add bean sprouts and garlic chives, toss briefly. Plate with crushed roasted peanuts, lime wedge, dried chili flakes, and extra bean sprouts on the side."},
        ],
    },
    {
        "title": "Green Curry (Gaeng Khiao Wan)",
        "cuisine": "Thai",
        "category": "Main Course",
        "text": "Aromatic coconut-based curry with green curry paste, Thai basil, bamboo shoots, and chicken or tofu.",
        "steps": [
            {"title": "Fry paste", "text": "Heat coconut cream in a wok until oil separates. Fry 3 tbsp green curry paste for 2 minutes until fragrant."},
            {"title": "Build curry", "text": "Add sliced chicken, stir to coat. Pour in 400ml coconut milk. Add halved Thai eggplant, bamboo shoots, kaffir lime leaves, and palm sugar. Simmer 15 minutes."},
            {"title": "Finish", "text": "Season with fish sauce. Stir in Thai basil leaves and sliced red chili. Serve over jasmine rice."},
        ],
    },
    {
        "title": "Tom Yum Soup",
        "cuisine": "Thai",
        "category": "Soup",
        "text": "Hot and sour Thai soup with shrimp, lemongrass, galangal, kaffir lime leaves, and chili paste.",
        "steps": [
            {"title": "Aromatics", "text": "Bring 1L chicken stock to a boil. Add 3 stalks smashed lemongrass, 5 slices galangal, 4 kaffir lime leaves, and 3 Thai chilies. Simmer 10 minutes."},
            {"title": "Cook", "text": "Add halved mushrooms and shrimp. Cook until shrimp turn pink, about 3 minutes. Stir in 2 tbsp nam prik pao (chili paste in oil)."},
            {"title": "Season", "text": "Remove from heat. Add 3 tbsp fish sauce and 4 tbsp lime juice. Garnish with cilantro. Do not boil after adding lime juice."},
        ],
    },
    {
        "title": "Mango Sticky Rice",
        "cuisine": "Thai",
        "category": "Dessert",
        "text": "Sweet glutinous rice soaked in coconut cream, served with fresh ripe mango slices and toasted mung beans.",
        "steps": [
            {"title": "Cook sticky rice", "text": "Soak 300g Thai glutinous rice overnight. Steam in a bamboo steamer lined with cheesecloth for 25 minutes until translucent and tender."},
            {"title": "Make coconut sauce", "text": "Heat 400ml coconut milk with 100g sugar and 1/2 tsp salt until dissolved. Pour 2/3 over hot rice, stir gently, and let absorb for 30 minutes."},
            {"title": "Serve", "text": "Mound coconut rice on a plate alongside sliced ripe Nam Dok Mai mango. Drizzle remaining coconut sauce and sprinkle toasted yellow mung beans on top."},
        ],
    },
    {
        "title": "Som Tum (Green Papaya Salad)",
        "cuisine": "Thai",
        "category": "Appetizer",
        "text": "Spicy, tangy shredded green papaya salad pounded in a mortar with chili, garlic, peanuts, dried shrimp, and lime.",
        "steps": [
            {"title": "Pound aromatics", "text": "In a large clay mortar, pound 2-3 Thai chilies and 3 garlic cloves into a rough paste."},
            {"title": "Add ingredients", "text": "Add 1 tbsp dried shrimp, 1 tbsp roasted peanuts, halved cherry tomatoes, and long beans. Bruise gently. Add shredded green papaya."},
            {"title": "Season and toss", "text": "Add 2 tbsp fish sauce, 2 tbsp lime juice, 1 tbsp palm sugar. Toss and bruise lightly to combine. Serve with sticky rice and raw cabbage."},
        ],
    },
    # ── French ──
    {
        "title": "Coq au Vin",
        "cuisine": "French",
        "category": "Main Course",
        "text": "Chicken braised in red Burgundy wine with lardons, mushrooms, pearl onions, and fresh thyme.",
        "steps": [
            {"title": "Brown chicken", "text": "Season chicken pieces with salt and pepper. Brown in batches in a Dutch oven with oil and butter until deep golden. Set aside."},
            {"title": "Build braise", "text": "In same pot, cook lardons until crispy. Add pearl onions and mushrooms, brown well. Add garlic, tomato paste, and flour. Deglaze with cognac. Pour in 1 bottle of Burgundy wine."},
            {"title": "Braise", "text": "Return chicken to pot. Add thyme, bay leaf, and chicken stock to just cover. Bring to simmer, cover, and transfer to 325°F oven for 1.5 hours until chicken is fall-off-the-bone tender."},
        ],
    },
    {
        "title": "Crème Brûlée",
        "cuisine": "French",
        "category": "Dessert",
        "text": "Rich vanilla custard with a crisp caramelized sugar crust, cracked with a spoon tableside.",
        "steps": [
            {"title": "Make custard", "text": "Heat 600ml heavy cream with a split vanilla bean until steaming. Whisk 6 egg yolks with 100g sugar until pale. Slowly temper cream into yolks. Strain through a fine sieve."},
            {"title": "Bake", "text": "Pour into 6 ramekins. Place in a water bath. Bake at 300°F for 45-50 minutes until set but still wobbly in the center. Refrigerate at least 4 hours."},
            {"title": "Caramelize", "text": "Sprinkle a thin even layer of white sugar on top. Torch with a kitchen blowtorch until the sugar melts and turns deep amber. Let harden 1 minute before serving."},
        ],
    },
    {
        "title": "French Onion Soup",
        "cuisine": "French",
        "category": "Soup",
        "text": "Deeply caramelized onion soup topped with a crouton and melted Gruyère cheese, gratinéed under a broiler.",
        "steps": [
            {"title": "Caramelize onions", "text": "Thinly slice 6 large yellow onions. Cook in butter and olive oil over medium-low heat for 45-60 minutes, stirring occasionally, until deep mahogany brown."},
            {"title": "Build soup", "text": "Add 2 tbsp flour, cook 2 minutes. Deglaze with 250ml dry white wine. Add 1.5L beef broth, thyme, and bay leaf. Simmer 20 minutes. Season with salt, pepper, and a splash of cognac."},
            {"title": "Gratinée", "text": "Ladle soup into oven-safe bowls. Float a thick slice of toasted baguette on top. Cover with grated Gruyère cheese. Broil until cheese is bubbly and golden brown."},
        ],
    },
    {
        "title": "Ratatouille",
        "cuisine": "French",
        "category": "Main Course",
        "text": "Provençal vegetable stew with eggplant, zucchini, bell peppers, tomatoes, and herbs de Provence.",
        "steps": [
            {"title": "Prepare vegetables", "text": "Dice eggplant, zucchini, bell peppers, onion, and tomatoes into uniform 2cm cubes. Keep each vegetable separate."},
            {"title": "Cook in stages", "text": "Sauté each vegetable separately in olive oil until lightly browned. This preserves individual flavors and textures. Season each batch with salt."},
            {"title": "Combine and simmer", "text": "Combine all vegetables in a large pot with crushed garlic, herbs de Provence, and tomato paste. Simmer covered for 30 minutes. Finish with fresh basil and a drizzle of olive oil."},
        ],
    },
    {
        "title": "Croissants",
        "cuisine": "French",
        "category": "Dessert",
        "text": "Buttery, flaky laminated pastry with 27 layers of dough and butter, shaped into crescents.",
        "steps": [
            {"title": "Make détrempe", "text": "Mix 500g bread flour, 60g sugar, 10g salt, 10g yeast, 300ml cold milk, and 30g softened butter. Knead until smooth. Refrigerate overnight."},
            {"title": "Laminate", "text": "Pound 280g cold butter into a flat square. Enclose in dough. Roll and fold three times (letter folds), chilling 1 hour between each fold. This creates 27 alternating layers."},
            {"title": "Shape and bake", "text": "Roll dough 5mm thick. Cut triangles and roll into crescent shapes. Proof at 78°F for 2 hours until doubled and jiggly. Egg wash. Bake at 400°F for 15-18 minutes until deeply golden and shatteringly flaky."},
        ],
    },
    # ── More diverse ──
    {
        "title": "Korean Bibimbap",
        "cuisine": "Korean",
        "category": "Main Course",
        "text": "Mixed rice bowl topped with sautéed vegetables, gochujang, fried egg, and optional bulgogi beef. Served in a hot stone bowl for crispy rice.",
        "steps": [
            {"title": "Prepare toppings", "text": "Separately sauté spinach, bean sprouts, carrots, zucchini, and shiitake mushrooms. Season each with sesame oil and salt. Prepare pickled radish."},
            {"title": "Assemble", "text": "Place hot rice in a sizzling stone bowl brushed with sesame oil. Arrange toppings in sections around the bowl. Place a fried egg in the center. Add 2 tbsp gochujang."},
            {"title": "Serve", "text": "Bring to table sizzling. Let the bottom rice get crispy against the hot stone (nurungji). Mix everything together before eating."},
        ],
    },
    {
        "title": "Ethiopian Doro Wat",
        "cuisine": "Ethiopian",
        "category": "Main Course",
        "text": "Spicy chicken stew cooked in berbere spice paste with onions, niter kibbeh (spiced butter), and hard-boiled eggs. Served on injera.",
        "steps": [
            {"title": "Make base", "text": "Slowly cook 6 finely diced onions in a dry pot for 30-40 minutes until very soft and deeply browned. No oil needed — the onions release their own moisture."},
            {"title": "Build wat", "text": "Add niter kibbeh and 4 tbsp berbere spice. Cook 5 minutes until fragrant and oil separates. Add chicken legs, turn to coat. Add water to half-cover. Simmer 45 minutes."},
            {"title": "Finish", "text": "Score hard-boiled eggs and add to stew for final 15 minutes. Season with salt and cardamom. Serve on injera bread, eating with your hands."},
        ],
    },
    {
        "title": "Greek Moussaka",
        "cuisine": "Greek",
        "category": "Main Course",
        "text": "Layered casserole of eggplant, spiced ground lamb with tomato sauce, and creamy béchamel top. Baked until golden.",
        "steps": [
            {"title": "Prepare eggplant", "text": "Slice 3 large eggplants into 1cm rounds. Salt and rest 30 minutes to draw out moisture. Pat dry and brush with olive oil. Roast at 400°F for 20 minutes."},
            {"title": "Make meat sauce", "text": "Brown 500g ground lamb with diced onion and garlic. Add tomato sauce, red wine, cinnamon stick, allspice, and bay leaf. Simmer 30 minutes until thick."},
            {"title": "Assemble and bake", "text": "Layer eggplant slices and meat sauce in a deep baking dish. Top with thick béchamel sauce enriched with egg yolks and nutmeg. Sprinkle with Parmesan. Bake at 375°F for 45 minutes until golden and bubbly."},
        ],
    },
    {
        "title": "Peruvian Ceviche",
        "cuisine": "Peruvian",
        "category": "Appetizer",
        "text": "Fresh sea bass cured in lime juice (leche de tigre) with red onion, ají limo chili, cilantro, and sweet potato.",
        "steps": [
            {"title": "Make leche de tigre", "text": "Blend lime juice, fish trimmings, celery, ginger, garlic, ají limo, salt, and ice. Strain. This is the curing liquid."},
            {"title": "Cure fish", "text": "Cut 500g fresh sea bass into 2cm cubes. Toss with leche de tigre, thinly sliced red onion, and cilantro. Let cure for 5 minutes only — the fish should be raw in the center."},
            {"title": "Serve", "text": "Plate ceviche with boiled sweet potato slices, large-kernel Peruvian corn (choclo), and crispy cancha corn. Serve immediately."},
        ],
    },
    {
        "title": "Moroccan Lamb Tagine",
        "cuisine": "Moroccan",
        "category": "Main Course",
        "text": "Slow-cooked lamb shoulder with apricots, almonds, saffron, cinnamon, and preserved lemons in a conical clay pot.",
        "steps": [
            {"title": "Brown lamb", "text": "Season 1kg lamb shoulder chunks with salt, pepper, cumin, and cinnamon. Brown in olive oil in the tagine base or a heavy pot."},
            {"title": "Build tagine", "text": "Add sliced onions, garlic, ginger, saffron threads, honey, and chicken stock. Arrange dried apricots and preserved lemon quarters on top. Cover with conical lid."},
            {"title": "Slow cook", "text": "Cook at 300°F for 2.5-3 hours until lamb is meltingly tender. Garnish with toasted almonds and fresh cilantro. Serve with couscous."},
        ],
    },
    {
        "title": "Vietnamese Pho",
        "cuisine": "Vietnamese",
        "category": "Soup",
        "text": "Aromatic beef noodle soup with clear star anise and cinnamon-scented broth, rice noodles, and thinly sliced beef.",
        "steps": [
            {"title": "Make broth", "text": "Char onions and ginger under a broiler. Simmer 2kg beef bones and oxtail in water for 6-8 hours, skimming regularly. Add charred aromatics, star anise, cinnamon, cloves, and coriander seeds for last 2 hours."},
            {"title": "Prepare bowls", "text": "Cook flat rice noodles (banh pho) according to package. Thinly slice raw eye of round beef against the grain."},
            {"title": "Assemble", "text": "Place noodles in deep bowls. Arrange raw beef slices on top. Ladle boiling hot broth over to cook the beef instantly. Serve with Thai basil, bean sprouts, lime, hoisin, and sriracha on the side."},
        ],
    },
    {
        "title": "Spanish Paella Valenciana",
        "cuisine": "Spanish",
        "category": "Main Course",
        "text": "Saffron-scented rice dish from Valencia with chicken, rabbit, green beans, white beans, and snails cooked over wood fire.",
        "steps": [
            {"title": "Build sofrito", "text": "In a wide paella pan over high heat, brown chicken and rabbit pieces in olive oil. Add grated tomato and cook until darkened and caramelized. Add smoked paprika."},
            {"title": "Cook rice", "text": "Add 1.5L hot stock infused with saffron. Bring to a boil, add green beans and white beans. When boiling again, sprinkle in 400g Bomba rice evenly. Cook 18-20 minutes without stirring."},
            {"title": "Socarrat", "text": "In the last 2 minutes, increase heat to create the socarrat — the prized crispy caramelized rice on the bottom. Remove from heat, cover with foil, and rest 5 minutes. Serve with lemon wedges."},
        ],
    },
    {
        "title": "Lebanese Hummus",
        "cuisine": "Lebanese",
        "category": "Appetizer",
        "text": "Silky smooth chickpea dip with tahini, lemon juice, garlic, and olive oil. Served with warm pita bread.",
        "steps": [
            {"title": "Cook chickpeas", "text": "Soak 250g dried chickpeas overnight with 1 tsp baking soda. Drain, cover with fresh water and 1 tsp baking soda. Boil until very soft and skins slip off easily, about 45 minutes."},
            {"title": "Blend", "text": "Process chickpeas with 80g tahini, juice of 2 lemons, 1 clove garlic, salt, and ice water in a food processor for 4-5 minutes until incredibly smooth and creamy."},
            {"title": "Serve", "text": "Spread on a plate, creating a well in the center. Pour extra virgin olive oil and sprinkle with paprika and whole chickpeas. Serve with warm pita."},
        ],
    },
    {
        "title": "Brazilian Feijoada",
        "cuisine": "Brazilian",
        "category": "Main Course",
        "text": "Black bean stew with multiple cuts of pork (ribs, sausage, ears, tail), served with rice, farofa, collard greens, and orange slices.",
        "steps": [
            {"title": "Soak and prep", "text": "Soak 500g dried black beans overnight. Separately soak salted pork ribs, ears, and tail to remove excess salt. Cut linguiça sausage into rounds."},
            {"title": "Cook stew", "text": "In a large pot, combine beans, all pork cuts, smoked sausage, bay leaves, and onion. Cover with water and simmer for 3-4 hours until beans are creamy and meat is fall-apart tender."},
            {"title": "Serve", "text": "Serve with white rice, sautéed collard greens, farofa (toasted cassava flour), orange slices, and hot pepper sauce on the side. This is a Saturday tradition in Brazil."},
        ],
    },
    {
        "title": "Turkish Lahmacun",
        "cuisine": "Turkish",
        "category": "Main Course",
        "text": "Thin crispy flatbread topped with spiced lamb mince, tomatoes, peppers, and herbs. Rolled up with parsley and lemon.",
        "steps": [
            {"title": "Make dough", "text": "Mix 300g flour, salt, 1 tsp sugar, and 5g yeast with 180ml warm water and 1 tbsp olive oil. Knead until smooth and elastic. Rest 1 hour."},
            {"title": "Prepare topping", "text": "Process 300g lamb mince with 1 onion, 2 tomatoes, 1 red pepper, garlic, parsley, red pepper flakes, cumin, and salt into a smooth paste that spreads easily."},
            {"title": "Bake", "text": "Roll dough very thin into circles. Spread meat mixture in a paper-thin layer to the edges. Bake directly on a pizza stone at 500°F for 6-8 minutes until edges are crispy. Squeeze lemon, add parsley, and roll up to eat."},
        ],
    },
    # ── A few more to reach 50 ──
    {
        "title": "Chinese Mapo Tofu",
        "cuisine": "Chinese",
        "category": "Main Course",
        "text": "Sichuan dish of silken tofu in a fiery, numbing sauce with doubanjiang, ground pork, Sichuan peppercorn, and fermented black beans.",
        "steps": [
            {"title": "Prepare tofu", "text": "Cut 400g silken tofu into 2cm cubes. Gently poach in salted boiling water for 3 minutes. This firms the tofu and prevents breaking during cooking."},
            {"title": "Make sauce", "text": "Stir-fry 100g ground pork in oil until crispy. Add 2 tbsp doubanjiang (chili bean paste), fermented black beans, and garlic. Cook until oil turns red."},
            {"title": "Combine", "text": "Add stock, soy sauce, and drained tofu cubes. Simmer 5 minutes. Thicken with cornstarch slurry. Finish with ground roasted Sichuan peppercorn, sesame oil, and sliced green onion."},
        ],
    },
    {
        "title": "Jamaican Jerk Chicken",
        "cuisine": "Jamaican",
        "category": "Main Course",
        "text": "Chicken marinated in a fiery jerk paste of Scotch bonnet peppers, allspice, thyme, garlic, and soy sauce, slow-grilled over pimento wood.",
        "steps": [
            {"title": "Make jerk paste", "text": "Blend 6 Scotch bonnet peppers, 2 tbsp allspice, bunch of thyme, 8 garlic cloves, 4 green onions, soy sauce, lime juice, brown sugar, nutmeg, and cinnamon into a thick paste."},
            {"title": "Marinate", "text": "Score chicken legs deeply. Rub jerk paste thoroughly into all cuts and surfaces. Marinate overnight in the refrigerator."},
            {"title": "Grill", "text": "Grill over indirect heat (ideally pimento wood charcoal) for 1-1.5 hours, turning occasionally, until charred outside and cooked through. The smoke and spice create the authentic jerk flavor."},
        ],
    },
    {
        "title": "Argentinian Chimichurri Steak",
        "cuisine": "Argentinian",
        "category": "Main Course",
        "text": "Thick-cut ribeye grilled over wood fire, served with fresh chimichurri sauce of parsley, oregano, garlic, and red wine vinegar.",
        "steps": [
            {"title": "Make chimichurri", "text": "Finely chop 1 cup flat-leaf parsley, 4 garlic cloves, 1 tbsp dried oregano. Mix with 1/3 cup red wine vinegar, 2/3 cup olive oil, red pepper flakes, salt, and pepper. Rest at least 1 hour."},
            {"title": "Grill steak", "text": "Season 2 thick-cut ribeyes generously with coarse salt only. Grill over hot wood embers for 5-6 minutes per side for medium-rare. Rest 10 minutes."},
            {"title": "Serve", "text": "Slice steak against the grain. Spoon chimichurri sauce generously over the top. Serve with grilled provoleta cheese and a simple salad."},
        ],
    },
    {
        "title": "Polish Pierogi",
        "cuisine": "Polish",
        "category": "Main Course",
        "text": "Filled dumplings with potato-cheese, sauerkraut-mushroom, or meat filling. Boiled then pan-fried in butter with onions.",
        "steps": [
            {"title": "Make dough", "text": "Mix 400g flour, 1 egg, 120ml warm water, pinch of salt, and 1 tbsp sour cream. Knead until smooth and pliable. Rest 30 minutes covered."},
            {"title": "Prepare filling", "text": "For potato-cheese: mash 500g boiled potatoes with 200g farmer's cheese (twaróg), sautéed onion, salt, and pepper. For sauerkraut: cook drained sauerkraut with rehydrated dried mushrooms and onion."},
            {"title": "Fill, boil, and fry", "text": "Roll dough thin, cut circles, place filling, fold and pinch edges sealed. Boil in salted water until they float plus 2 minutes. Pan-fry in butter with sliced onions until golden. Serve with sour cream."},
        ],
    },
    {
        "title": "Egyptian Koshari",
        "cuisine": "Egyptian",
        "category": "Main Course",
        "text": "Egypt's national dish: layers of rice, lentils, macaroni, and chickpeas topped with spiced tomato sauce and crispy fried onions.",
        "steps": [
            {"title": "Cook components", "text": "Separately cook: white rice, brown lentils, small elbow macaroni, and chickpeas. Each should be perfectly tender."},
            {"title": "Make sauces", "text": "Tomato sauce: sauté garlic in oil, add tomato sauce, vinegar, cumin, and chili. Simmer 15 minutes. Vinegar-garlic dressing: crush garlic with vinegar, cumin, and chili."},
            {"title": "Assemble", "text": "Layer in a bowl: rice, lentils, macaroni, and chickpeas. Ladle hot tomato sauce on top. Crown with a generous pile of crispy fried onion rings. Drizzle with vinegar-garlic dressing."},
        ],
    },
    {
        "title": "Filipino Adobo",
        "cuisine": "Filipino",
        "category": "Main Course",
        "text": "Chicken and pork braised in soy sauce, vinegar, garlic, bay leaves, and black peppercorns. The national dish of the Philippines.",
        "steps": [
            {"title": "Marinate", "text": "Combine 500g chicken thighs and 500g pork belly cubes with 120ml soy sauce, 120ml white vinegar, 1 head crushed garlic, bay leaves, and peppercorns. Marinate 1 hour."},
            {"title": "Braise", "text": "Transfer everything including marinade to a pot. Add 200ml water. Bring to a boil, then reduce to a simmer. Cook uncovered for 45 minutes until meat is very tender and sauce is reduced."},
            {"title": "Finish", "text": "Remove meat pieces and pan-fry in oil until browned and slightly crispy on edges. Return to sauce. Serve over steamed white rice with the rich braising sauce."},
        ],
    },
]

# Labeled training data: (query, recipe_title, relevant: bool)
# Used to train the MLP reranker
TRAINING_DATA = [
    ("how to make pizza dough", "Classic Margherita Pizza", True),
    ("how to make pizza dough", "Naan Bread", False),
    ("how to make pizza dough", "Croissants", False),
    ("saffron rice recipe", "Risotto alla Milanese", True),
    ("saffron rice recipe", "Sushi Rice", False),
    ("saffron rice recipe", "Spanish Paella Valenciana", True),
    ("spicy noodle soup", "Tonkotsu Ramen", True),
    ("spicy noodle soup", "Pad Thai", False),
    ("spicy noodle soup", "Vietnamese Pho", True),
    ("spicy noodle soup", "Miso Soup", False),
    ("chocolate dessert", "Tiramisu", True),
    ("chocolate dessert", "Churros", True),
    ("chocolate dessert", "Crème Brûlée", False),
    ("chocolate dessert", "Mango Sticky Rice", False),
    ("grilled meat recipe", "Argentinian Chimichurri Steak", True),
    ("grilled meat recipe", "Jamaican Jerk Chicken", True),
    ("grilled meat recipe", "Tacos al Pastor", True),
    ("grilled meat recipe", "Palak Paneer", False),
    ("grilled meat recipe", "Guacamole", False),
    ("creamy curry", "Butter Chicken (Murgh Makhani)", True),
    ("creamy curry", "Green Curry (Gaeng Khiao Wan)", True),
    ("creamy curry", "Chicken Katsu Curry", True),
    ("creamy curry", "Peruvian Ceviche", False),
    ("creamy curry", "Lebanese Hummus", False),
    ("dumpling recipe", "Gyoza", True),
    ("dumpling recipe", "Polish Pierogi", True),
    ("dumpling recipe", "Samosa", True),
    ("dumpling recipe", "Elote (Mexican Street Corn)", False),
    ("dumpling recipe", "Ratatouille", False),
    ("french pastry", "Croissants", True),
    ("french pastry", "Crème Brûlée", True),
    ("french pastry", "Churros", False),
    ("french pastry", "Naan Bread", False),
    ("vegetarian main course", "Palak Paneer", True),
    ("vegetarian main course", "Ratatouille", True),
    ("vegetarian main course", "Chinese Mapo Tofu", True),
    ("vegetarian main course", "Coq au Vin", False),
    ("vegetarian main course", "Tonkotsu Ramen", False),
    ("bean stew", "Brazilian Feijoada", True),
    ("bean stew", "Egyptian Koshari", True),
    ("bean stew", "Mole Poblano", False),
    ("bean stew", "Pad Thai", False),
    ("street food", "Tacos al Pastor", True),
    ("street food", "Elote (Mexican Street Corn)", True),
    ("street food", "Turkish Lahmacun", True),
    ("street food", "Som Tum (Green Papaya Salad)", True),
    ("street food", "Coq au Vin", False),
    ("street food", "Risotto alla Milanese", False),
    ("hot and sour soup", "Tom Yum Soup", True),
    ("hot and sour soup", "Miso Soup", False),
    ("hot and sour soup", "French Onion Soup", False),
    ("braised meat dish", "Coq au Vin", True),
    ("braised meat dish", "Filipino Adobo", True),
    ("braised meat dish", "Moroccan Lamb Tagine", True),
    ("braised meat dish", "Peruvian Ceviche", False),
    ("braised meat dish", "Guacamole", False),
    ("avocado dish", "Guacamole", True),
    ("avocado dish", "Tonkotsu Ramen", False),
    ("fresh raw fish", "Peruvian Ceviche", True),
    ("fresh raw fish", "Sushi Rice", True),
    ("fresh raw fish", "Butter Chicken (Murgh Makhani)", False),
    ("rice bowl", "Korean Bibimbap", True),
    ("rice bowl", "Biryani", True),
    ("rice bowl", "Egyptian Koshari", True),
    ("rice bowl", "Croissants", False),
    ("egg based dish", "Pasta Carbonara", True),
    ("egg based dish", "Crème Brûlée", True),
    ("egg based dish", "Ethiopian Doro Wat", True),
    ("egg based dish", "Lebanese Hummus", False),
    ("slow cooked", "Moroccan Lamb Tagine", True),
    ("slow cooked", "Brazilian Feijoada", True),
    ("slow cooked", "Tonkotsu Ramen", True),
    ("slow cooked", "Bruschetta al Pomodoro", False),
    ("appetizer dip", "Guacamole", True),
    ("appetizer dip", "Lebanese Hummus", True),
    ("appetizer dip", "Biryani", False),
    ("appetizer dip", "Coq au Vin", False),
    ("coconut based dish", "Green Curry (Gaeng Khiao Wan)", True),
    ("coconut based dish", "Mango Sticky Rice", True),
    ("coconut based dish", "Tom Yum Soup", False),
    ("coconut based dish", "Pasta Carbonara", False),
]
